Feat/146 date of next new moon
youry/AstroCal pull request #28
Opened 2022-10-04 21:06 UTC by Logan-Campbell

Functionality for getting next date of new moon and test cases

2022-10-04 21:27 UTC, mrstarch approved these changes

2022-10-04 22:21 UTC, FreddieBanfield requested changes
Please may you complete these two changes.

2022-10-04 22:21 UTC, FreddieBanfield commented on tests/test_DateOfNextNewMoon.py
> +from control import getDateOfNextNewMoon
Please add these tests (call the tests you created in test_DateOfNectNewMoon.py) to the test_all.py file, as we will run all unit tests at one time, not as individual files.
![image](https://user-images.githubusercontent.com/58247240/193940246-b872751c-6b6b-47ec-ad1f-1f2460505c2b.png)

2022-10-04 22:21 UTC, FreddieBanfield commented on AstroCal/control/control.py
> +
Not seeing any changes to console_output.py. That means there is no way for me to see this in the console at the moment. Please add an extra option in the moon_menu in console_output.py. 
![image](https://user-images.githubusercontent.com/58247240/193940723-1e6bb411-1872-4871-b212-e578df06fd6d.png)

2022-10-05 02:24 UTC, FreddieBanfield approved these changes
Looks great!

2022-10-05 02:24 UTC, merged